plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'es.miw.tfm.linkal'
    compileSdk 36

    defaultConfig {
        applicationId "es.miw.tfm.linkal"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            enableUnitTestCoverage true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation (libs.retrofit)
    implementation libs.converter.gson
    implementation libs.gson
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    testImplementation libs.junit
    testImplementation libs.mockito.core
    testImplementation libs.arch.core.testing
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
tasks.register('jacocoTestReport', JacocoReport) {
    dependsOn 'testDebugUnitTest'

    reports {
        xml.required  = true
        html.required = true
    }

    def classFilter = [
            '**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*',
            '**/*Test*.*', 'android/**/*.*'
    ]
    def compiledClasses = fileTree(
            dir: "${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes",
            excludes: classFilter
    )

    classDirectories.setFrom(files(compiledClasses))
    sourceDirectories.setFrom(files(["${project.projectDir}/src/main/java"]))

    executionData.setFrom(fileTree(
            dir: "${buildDir}",
            includes: ["outputs/unit_test_code_coverage/debugUnitTest/*.exec"]
    ))
}